In [1]:
#1) C
#2) D
#3a) 1.8
#3b) 3.1

In [2]:
import numpy as np

A = np.array([1, 3, 5, 7, 13])
A

array([ 1,  3,  5,  7, 13])

In [4]:
(A - np.min(A)) / (np.max(A) - np.min(A))

array([0.        , 0.16666667, 0.33333333, 0.5       , 1.        ])

In [5]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit_transform(A.reshape(-1, 1))

array([[0.        ],
       [0.16666667],
       [0.33333333],
       [0.5       ],
       [1.        ]])

In [6]:
(A - np.mean(A)) / np.std(A, ddof = 1)

array([-1.04249338, -0.60812114, -0.1737489 ,  0.26062335,  1.56374007])

In [7]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit_transform(A.reshape(-1, 1))

array([[-1.16554303],
       [-0.6799001 ],
       [-0.19425717],
       [ 0.29138576],
       [ 1.74831455]])